apiVersion: check.mrudz.io/v1alpha1
kind: Check
metadata:
  name: example-check
spec:
  forProvider:
    name: example-check
    host: example.com
    type: http
    resolution: 5
  providerConfigRef:
    name: default